import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";

//TODO: Have main page pass API JSON objects to individual componenents(?)
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header  />
      <main></main>
    </div>
  );
};

export default Home;
