import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GenerationCounter from '../components/GenerationCounter/GenerationCounter'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GenerationCounter></GenerationCounter>
      <main >

      </main> 
    </div>
  )
}

export default Home
